<?php

//todo: if class is empty, why to create it?

namespace Acme\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BatteriesPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatteriesPackRepository extends EntityRepository
{
}
